config/routes.rb
Rails.application.routes.draw do
  resources :admin, only: [:index] do
    collection do
      post :crisis
    end
  end

  resources :missions

  resources :projects

  resources :resources

  resources :events

  resources :factions

  get "intel/home"

  get "systems/overview"
  get "systems/power"
  get "systems/structural"
  get "systems/information"
  get "systems/defensive"
  get "systems/offensive"
  get "systems/transit"
  get "systems/environmental"

  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  include VisibleScope

  STATUSES = ['hidden', 'available', 'ignored', 'active', 'resolved', 'failed']

  validates :status, inclusion: { in: STATUSES }

end

app/models/faction.rb
class Faction < ApplicationRecord

end

app/models/mission.rb
class Mission < ApplicationRecord
  include VisibleScope

  STATUSES = ['hidden', 'available', 'active', 'complete']

  has_many :projects

  validates :status, inclusion: { in: STATUSES }
end

app/models/project.rb
class Project < ApplicationRecord
  include VisibleScope

  STATUSES = ['hidden', 'pending', 'approved', 'complete', 'rejected', 'halted']

  belongs_to :mission

  validates :status, inclusion: { in: STATUSES }
  
  scope :unlocked, -> { joins('left join missions on projects.mission_id = missions.id').where("projects.mission_id is null OR missions.status like ?", 'complete') }
end

app/models/resource.rb
class Resource < ApplicationRecord
  include VisibleScope
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    if session[:confirm_admin] || params[:confirm]
      session[:confirm_admin] = true
    else
      redirect_to root_path and return
    end
    @resources = Resource.all
    @projects = Project.includes(:mission).order(:id).all
    @missions = Mission.order(:number).all
    @factions = Faction.order(:fleet).reverse
    @events = Event.all
  end

  def crisis
    Apeiron::Application.config.crisis = (params[:set]=='1')
    redirect_to admin_index_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  layout false

  def index
    @events = Event.visible.all
  end

  def update
    @event = Event.find(params[:id])
    @event.update(event_params)
    redirect_to admin_index_path
  end

  private

  def event_params
    params.require(:event).permit!
  end

end

app/controllers/factions_controller.rb
class FactionsController < ApplicationController
  layout false

  def index
    @factions = Faction.by_power.all
  end

  def update
    @faction = Faction.find(params[:id])
    @faction.update(faction_params)
    redirect_to admin_index_path
  end

  private

  def faction_params
    params.require(:faction).permit!
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @crisis = Apeiron::Application.config.crisis
  end

end

app/controllers/intel_controller.rb
class IntelController < ApplicationController
  layout false

  def home
    @factions = Faction.all
    @events = Event.visible.all
  end
end

app/controllers/missions_controller.rb
class MissionsController < ApplicationController
  layout false

  def index
    @missions = Mission.visible.all
  end

  def update
    @mission = Mission.find(params[:id])
    @mission.update(mission_params)
    redirect_to admin_index_path
  end

  private

  def mission_params
    params.require(:mission).permit!
  end

end

app/controllers/systems_controller.rb
class SystemsController < ApplicationController
  layout false
  def overview
  end

  def power
  end

  def structural
  end

  def information
  end

  def defensive
  end

  def offensive
  end

  def transit
    @drive_config = [
      ['Configuration name:', '<i>Itera Astratis</i> (default)'],
      ['Stelleration coefficient:', '0.28215'],
      ['Compression constant:', '307.1 GeV'],
      ['Power load (% core output):', 'Minimum: 16% - Optimal: 23% - Apex: 31%'],
      ['Coil charge:', '29.291 TeV'],
      ['Field flux density (Φ/A):', '34 Tesla'], 
        # Fun fact: This is probably enough magnetic flux to make a human levitate via diamagnetism.
        # See http://physics.stackexchange.com/questions/172861/how-much-magnetic-field-will-be-required-to-levitate-a-human
      ['Drive cycle inversions:', '6038/sec'],
      ['Manifold reinforcement matrix:', 'off'],
      ['Active drive management:', 'off']
    ]
  end

  def environmental
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/intel_helper.rb
module IntelHelper
end

app/helpers/missions_helper.rb
module MissionsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/systems_helper.rb
module SystemsHelper
end

app/views/admin/index.html.haml
%h1 Admin
%p 
  Crisis mode:
  = Apeiron::Application.config.crisis
  = button_to("Turn On", crisis_admin_index_path({set: 1}), method: :post )
  = button_to("Turn Off", crisis_admin_index_path({set: 0}), method: :post)

%h2 Projects
%table.admin
  %thead
    %tr{}
      %td ID
      %td Name
      %td Proposer
      %td Description
      %td Approved At
      %td Status
      %td Prerequisite Mission
      %td Actions
  %tbody
    - @projects.each do |project|
      %tr{id: "project-row-#{project.id}"}
        %td= project.id
        %td= project.name.try(:html_safe)
        %td= project.proposer.try(:html_safe)
        %td= truncate(project.description, length: 60).try(:html_safe)
        %td= "#{time_ago_in_words(project.approved_at)} ago" if project.approved_at
        %td= project.status
        %td= project.mission.name if project.mission
        %td= link_to('Edit', '', class: 'edit-project', id: "edit-project-#{project.id}", data: {project_id: project.id})
      %tr.form.hidden{id: "project-form-#{project.id}"}
        = simple_form_for project do |f|
          %td
          %td= f.input :name, as: :string, label: false
          %td= f.input :proposer, as: :string, label: false
          %td= f.input :description, as: :text, input_html: { :style=> 'width: 100%;', :rows => 6}, label: false
          %td= f.input :approved_at, as: :date, label: false
          %td= f.input :status, collection: Project::STATUSES, label: false
          %td= f.input :mission_id, collection: @missions, label: false
          %td
            =f.submit
            %br
            %button.cancel-project-form{id: "project-cancel-button-#{project.id}"}
              Cancel

%h2 Resources
%table.admin
  %thead
    %tr{}
      %td ID
      %td Name
      %td Description
      %td Quantity
      %td Actions
  %tbody
    - @resources.each do |resource|
      %tr{id: "resource-row-#{resource.id}"}
        %td= resource.id
        %td= resource.name.try(:html_safe)
        %td= truncate(resource.description, length: 60).try(:html_safe)
        %td= "#{resource.quantity}#{resource.unit}"
        %td= link_to('Edit', '', class: 'edit-resource', id: "edit-resource-#{resource.id}", data: {resource_id: resource.id})
      %tr.form.hidden{id: "resource-form-#{resource.id}"}
        = simple_form_for resource do |f|
          %td
          %td= f.input :name, as: :string, label: false
          %td= f.input :description, as: :text, input_html: { :style=> 'width: 100%;', :rows => 6}, label: false
          %td
            = f.input :quantity, as: :string, label: false
            = f.input :unit, label: false
          %td
            =f.submit
            %br
            %button.cancel-resource-form{id: "resource-cancel-button-#{resource.id}"}
              Cancel

%h2 Factions
%table.admin
  %thead
    %tr{}
      %td ID
      %td Name
      %td Fleet Strength
      %td Territory
      %td Notes
      %td Actions
  %tbody
    - @factions.each do |faction|
      %tr{id: "faction-row-#{faction.id}"}
        %td= faction.id
        %td= faction.name
        %td= faction.fleet
        %td= faction.territory
        %td= faction.notes
        %td= link_to('Edit', '', class: 'edit-faction', id: "edit-faction-#{faction.id}", data: {faction_id: faction.id})
      %tr.form.hidden{id: "faction-form-#{faction.id}"}
        = simple_form_for faction do |f|
          %td
          %td= f.input :name, as: :string, label: false
          %td= f.input :fleet, as: :string, label: false
          %td= f.input :territory, as: :string, label: false
          %td= f.input :notes, as: :text, input_html: { :style=> 'width: 100%;', :rows => 6}, label: false
          %td
            =f.submit
            %br
            %button.cancel-faction-form{id: "faction-cancel-button-#{faction.id}"}
              Cancel

%h2 Missions
%table.admin
  %thead
    %tr{}
      %td ID
      %td Number
      %td Name
      %td Briefing
      %td Resolution
      %td Status
      %td Actions
  %tbody
    - @missions.each do |mission|
      %tr{id: "mission-row-#{mission.id}"}
        %td= mission.id
        %td= mission.number
        %td= mission.name
        %td= mission.brief.try(:html_safe)
        %td= mission.resolution.try(:html_safe)
        %td= mission.status
        %td= link_to('Edit', '', class: 'edit-mission', id: "edit-mission-#{mission.id}", data: {mission_id: mission.id})
      %tr.form.hidden{id: "mission-form-#{mission.id}"}
        = simple_form_for mission do |f|
          %td
          %td= f.input :number, as: :string, label: false
          %td= f.input :name, as: :string, label: false
          %td= f.input :brief, as: :text, input_html: { :style=> 'width: 100%;', :rows => 6}, label: false
          %td= f.input :resolution, as: :text, input_html: { :style=> 'width: 100%;', :rows => 6}, label: false
          %td= f.input :status, collection: Mission::STATUSES, label: false
          %td
            =f.submit
            %br
            %button.cancel-mission-form{id: "mission-cancel-button-#{mission.id}"}
              Cancel
%h2 Dark Events
%table.admin
  %thead
    %tr{}
      %td ID
      %td Name
      %td Description
      %td Action Taken
      %td Resolution
      %td Status
      %td Actions
  %tbody
    - @events.each do |event|
      %tr{id: "event-row-#{event.id}"}
        %td= event.id
        %td= event.name
        %td= event.description.try(:html_safe)
        %td= event.action
        %td= event.resolution.try(:html_safe)
        %td= event.status
        %td= link_to('Edit', '', class: 'edit-event', id: "edit-event-#{event.id}", data: {event_id: event.id})
      %tr.form.hidden{id: "event-form-#{event.id}"}
        = simple_form_for event do |f|
          %td
          %td= f.input :name, as: :string, label: false
          %td= f.input :description, as: :text, input_html: { :style=> 'width: 100%;', :rows => 6}, label: false
          %td= f.input :action, as: :string, label: false
          %td= f.input :resolution, as: :text, input_html: { :style=> 'width: 100%;', :rows => 6}, label: false
          %td= f.input :status, collection: Event::STATUSES, label: false
          %td
            =f.submit
            %br
            %button.cancel-event-form{id: "event-cancel-button-#{event.id}"}
              Cancel

:javascript
  $(document).ready(function() {
    Apeiron.admin.onDocumentReady();
  });

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Apeiron</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>